services:
  nvidia_pytorch2:
    build:
      context: .
      dockerfile: Dockerfile
    image: nvcr.io/nvidia/pytorch:22.10-py3
    container_name: web-container
    
    environment:
      - LABEL_STUDIO_HOSTNAME=http://192.168.0.100:8080/
      - config_file=/home/checkpoints/faster_rcnn_r50_fpn_1x_coco.py
      - checkpoint_file=/home/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
      - device=cuda:0

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/root
    ports:
      - "7777:7777"
    command:
      /bin/bash -c "cd /root/label-studio-ml-backend/ && \
      label-studio-ml start coco-detector --with --port=7777 "

    #   #   jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --port=6666
    #   #jupyter notebook --port=6666 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    #   nvidia-smi

    tty: true